config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root                            to: 'home#index'
  get 'auth/:provider/callback',  to: 'sessions#create'
  get 'logout',                   to: 'sessions#destroy'
  get 'physicians',               to: 'physicians#index'
  resources :appointments, only: [:show]

  namespace :api do
    namespace :v1 do
      resources :appointments, only: [:create, :index, :update, :show, :destroy]
      resources :physicians, only: [:create, :index]
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <title><%= content_for?(:title) ? yield(:title) : "MyMed" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <% if current_user  %>
      <nav>
        <div class='logo'>MyMed</div>
        <ul>
          <li class="home-nav"><i class="fa fa-home fa-2x" aria-hidden="true"></i><%= link_to "Home", root_path %></li>
          <li class="physicians-nav"><i class="fa fa-user-md fa-2x" aria-hidden="true"></i><%= link_to "Physicians", physicians_path %></li>
          <li class="logout"><%= link_to "Logout", logout_path %></li>
        </ul>
      </nav>
      <topNav></topNav>
      <% if flash[:notice] %>
        <div class="notice"><%= flash[:notice] %></div>
      <% end %>
      <div id="app"><%= yield %></div>
    <% else %>
      <div class='login'>
        <div class='login-topnav'></div>
        <div class='login-content'>
          <div class="welcome">Welcome to MyMed</div>
          <%= link_to "Sign in with Google", "/auth/google" %>
        </div>
      </div>
    <% end %>
    <%= javascript_include_tag "application" %>
  </body>
</html>